server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/auth_service
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

zulmaidi:
  app:
    jwtSecret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6356
    jwtCookieName: zulmaidi
    jwtExpirationMs: 86400000