server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://panjuak:maniadfd05@cluster0.2kast.mongodb.net/?retryWrites=true&w=majority
      database: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0